<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author      Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Diglin
 * @package     Diglin_Intercom
 * @copyright   Copyright (c) 2011-2015 Diglin (http://www.diglin.com)
 */

/* @var $this Diglin_Intercom_Block_Widget */
?>
<?php if ($this->isLoggedIn()): ?>
<script>
    window.intercomSettings = {
        name: "<?php echo $this->getCustomerName(); ?>",
        email: "<?php echo $this->getCustomerEmail(); ?>",
        created_at: <?php echo $this->getCustomerCreatedAt(); ?>,
        app_id: "<?php echo $this->getAppId(); ?>",
        user_id: "<?php echo $this->getCustomer()->getId(); ?>"
    };
</script>
<?php else: ?>
<script>
    window.intercomSettings = {
        app_id: "<?php echo $this->getAppId(); ?>"
    };
</script>
<?php endif; ?>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/<?php echo $this->getAppId(); ?>';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>
